export const robot=[
    {
        id:1,
        name:"sam",
        email:"sam22@gmail.com"
    },
    {
        id:2,
        name:"ram",
        email:"ram22@gmail.com"  
    },
    {
        id:3,
        name:"sham",
        email:"sham22@gmail.com"
    },
    {
        id:4,
        name:"rahul",
        email:"rahul2@gmail.com"
    },
    {
        id:5,
        name:"samy",
        email:"samy22@gmail.com"
    },
    {
        id:6,
        name:"samily",
        email:"samily22@gmail.com"
    },
    {
        id:7,
        name:"milli",
        email:"mm22@gmail.com"
    },
    {
        id:8,
        name:"baba",
        email:"baba22@gmail.com"
    }
]